"""
This type stub file was generated by pyright.
"""

import datetime
import pandas as pd
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, TypedDict, Union
from googleads import ad_manager

"""
Helpers for interacting with the Google Ad Manager API.

This module provides a set of classes to simplify interactions with various
services within the Google Ad Manager API. It handles client authentication,
service discovery, and provides methods for common operations like reporting,
forecasting, and managing audiences.
"""
PYTZ_TIMEZONE = ...
AD_UNIT_VIEW = ...
METRICS = ...
DIMENSIONS = ...
GAM_VERSION = ...
NETWORK_CODE = ...
APP_NAME = ...
Operator = Literal["AND", "OR"]

class AdUnitView(Enum):
    """Enum for the Ad Unit view in a report."""

    TOP_LEVEL = ...
    FLAT = ...

class KeyValuePair(TypedDict):
    """A TypedDict for a custom targeting key-value pair."""

    customTargetingKeyId: int
    id: int
    name: str
    displayName: str
    matchType: str
    status: Operator
    ...

class CustomCriteria(TypedDict):
    """A TypedDict for a custom criteria."""

    keyId: int
    valueIds: List[int]
    operator: Operator
    ...

class CustomCriteriaSubSet(TypedDict):
    """A TypedDict for a subset of custom criteria."""

    logicalOperator: Operator
    children: List[CustomCriteria]
    ...

class CustomCriteriaSet(TypedDict):
    """A TypedDict for a set of custom criteria."""

    logicalOperator: Operator
    children: List[CustomCriteriaSubSet]
    ...

class Targeting(TypedDict):
    """A TypedDict for targeting information."""

    customTargeting: CustomCriteriaSet
    ...

class TargetingPreset(TypedDict):
    """A TypedDict for a targeting preset."""

    id: int
    name: str
    targeting: Targeting
    ...

class Size(TypedDict):
    """A TypedDict for a size."""

    width: str
    height: str
    ...

class CreativePlaceholder(TypedDict):
    """A TypedDict for a creative placeholder."""

    size: Size
    ...

class ForecastItem(TypedDict):
    """A TypedDict for a forecast item."""

    date: datetime.date
    matched: int
    available: int
    possible: int
    name: str
    ...

class trafficItem(TypedDict):
    """A TypedDict for a traffic item."""

    date: datetime.date
    impressions: int
    ...

class GamClient(ad_manager.AdManagerClient):
    """
    A client for the Google Ad Manager API.

    This class extends the base ``ad_manager.AdManagerClient`` to simplify
    initialization with service account credentials.

    Methods
    -------
    get_service(service_name, gam_version)
        Get a service client for the Ad Manager API.
    get_data_downloader(gam_version)
        Get a data downloader for the Ad Manager API.
    """

    def __init__(self, app_name: str = ..., network_code: str = ...) -> None:
        """
        Initialise the GamClient.

        Parameters
        ----------
        app_name : str, optional
            The name of the application. Defaults to ``APP_NAME``.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        """
        ...

    def get_service(self, service_name: str, gam_version: str) -> Any:
        """
        Get a service client for the Ad Manager API.

        Parameters
        ----------
        service_name : str
            The name of the service to get.
        gam_version : str
            The version of the API to use.

        Returns
        -------
        Any
            An instance of the requested service client.
        """
        ...

    def get_data_downloader(self, gam_version: str) -> ad_manager.DataDownloader:
        """
        Get a data downloader for the Ad Manager API.

        Parameters
        ----------
        gam_version : str
            The version of the API to use.

        Returns
        -------
        googleads.ad_manager.DataDownloader
            A data downloader instance.
        """
        ...

class AudienceService:
    """
    A wrapper for the Audience service of the Ad Manager API.

    Methods
    -------
    create(name, description, custom_targeting, pageviews=1, recencydays=1, membershipexpirationdays=90, network_code=NETWORK_CODE)
        Create a new audience segment.
    list()
        List all first-party audience segments.
    list_all()
        List all audience segments of any type.
    update(audience_segment_id, name, description, custom_targeting_key_id, custom_targeting_value_id, pageviews=1, recencydays=1, membershipexpirationdays=90)
        Update an existing audience segment.
    """

    _service_name = ...
    _gam_service: Any
    def __init__(
        self, app_name: str = ..., network_code: str = ..., gam_version: str = ...
    ) -> None:
        """
        Initialise the AudienceService.

        Parameters
        ----------
        app_name : str, optional
            The name of the application. Defaults to ``APP_NAME``.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        gam_version : str, optional
            The version of the API to use. Defaults to ``GAM_VERSION``.
        """
        ...

    def create(
        self,
        name: str,
        description: str,
        custom_targeting: CustomCriteriaSet,
        pageviews: int = ...,
        recencydays: int = ...,
        membershipexpirationdays: int = ...,
        network_code: str = ...,
    ) -> None:
        """
        Create a new audience segment.

        Parameters
        ----------
        name : str
            The name of the audience segment.
        description : str
            The description of the audience segment.
        custom_targeting : CustomCriteriaSet
            The custom targeting rules for the audience.
        pageviews : int, optional
            The number of pageviews required. Defaults to 1.
        recencydays : int, optional
            The number of recency days. Defaults to 1.
        membershipexpirationdays : int, optional
            The membership expiration in days. Defaults to 90.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        """
        ...

    def list(self) -> List[Dict[str, Any]]:
        """
        List all first-party audience segments.

        Returns
        -------
        list[dict[str, Any]]
            A list of audience segment objects.
        """
        ...

    def list_all(self) -> List[Dict[str, Any]]:
        """
        List all audience segments of any type.

        Returns
        -------
        list[dict[str, Any]]
            A list of audience segment objects.
        """
        ...

    def update(
        self,
        audience_segment_id: int,
        name: str,
        description: str,
        custom_targeting_key_id: int,
        custom_targeting_value_id: int,
        pageviews: int = ...,
        recencydays: int = ...,
        membershipexpirationdays: int = ...,
    ) -> None:
        """
        Update an existing audience segment.

        Parameters
        ----------
        audience_segment_id : int
            The ID of the audience segment to update.
        name : str
            The new name for the audience segment.
        description : str
            The new description for the audience segment.
        custom_targeting_key_id : int
            The ID of the custom targeting key.
        custom_targeting_value_id : int
            The ID of the custom targeting value.
        pageviews : int, optional
            The number of pageviews required. Defaults to 1.
        recencydays : int, optional
            The number of recency days. Defaults to 1.
        membershipexpirationdays : int, optional
            The membership expiration in days. Defaults to 90.
        """
        ...

class NetworkService:
    """
    A wrapper for the Network service of the Ad Manager API.

    Methods
    -------
    effectiveRootAdUnitId()
        Get the effective root ad unit ID for the network.
    """

    _service_name = ...
    _gam_service: Any
    def __init__(
        self, app_name: str = ..., network_code: str = ..., gam_version: str = ...
    ) -> None:
        """
        Initialise the NetworkService.

        Parameters
        ----------
        app_name : str, optional
            The name of the application. Defaults to ``APP_NAME``.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        gam_version : str, optional
            The version of the API to use. Defaults to ``GAM_VERSION``.
        """
        ...

    def effective_root_ad_unit_id(self) -> int:
        """
        Get the effective root ad unit ID for the network.

        Returns
        -------
        int
            The root ad unit ID.
        """
        ...

class CustomTargetingService:
    """
    A wrapper for the CustomTargeting service of the Ad Manager API.

    Methods
    -------
    list(targeting_key_id)
        List all active key-value pairs for a given targeting key.
    delete(targeting_key_id, key_value_pairs)
        Delete a list of key-value pairs.
    update(key_value_pairs)
        Update a list of key-value pairs.
    create(created_values)
        Create a list of key-value pairs.
    """

    _service_name = ...
    _gam_service: Any
    def __init__(
        self, app_name: str = ..., network_code: str = ..., gam_version: str = ...
    ) -> None:
        """
        Initialise the CustomTargetingService.

        Parameters
        ----------
        app_name : str, optional
            The name of the application. Defaults to ``APP_NAME``.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        gam_version : str, optional
            The version of the API to use. Defaults to ``GAM_VERSION``.
        """
        ...

    def list(self, targeting_key_id: int) -> List[KeyValuePair]:
        """
        List all active key-value pairs for a given targeting key.

        Parameters
        ----------
        targeting_key_id : int
            The ID of the custom targeting key.

        Returns
        -------
        list[KeyValuePair]
            A list of key-value pair objects.
        """
        ...

    def delete(
        self, targeting_key_id: int, key_value_pairs: List[KeyValuePair]
    ) -> None:
        """
        Delete a list of key-value pairs.

        Parameters
        ----------
        targeting_key_id : int
            The ID of the custom targeting key.
        key_value_pairs : list[KeyValuePair]
            The list of key-value pairs to delete.
        """
        ...

    def update(self, key_value_pairs: List[KeyValuePair]) -> None:
        """
        Update a list of key-value pairs.

        Parameters
        ----------
        key_value_pairs : list[KeyValuePair]
            The list of key-value pairs to update.
        """
        ...

    def create(self, created_values: List[KeyValuePair]) -> None:
        """
        Create a list of key-value pairs.

        Parameters
        ----------
        created_values : list[KeyValuePair]
            The list of key-value pairs to create.
        """
        ...

class TargetingPresetService:
    """
    A wrapper for the TargetingPreset service of the Ad Manager API.

    Methods
    -------
    create(targeting)
        Create a list of targeting presets.
    update(targeting)
        Update a list of targeting presets.
    list_by_prefix(targeting_preset_prefix)
        List targeting presets that match a given prefix.
    """

    _service_name = ...
    _gam_service: Any
    def __init__(
        self, app_name: str = ..., network_code: str = ..., gam_version: str = ...
    ) -> None:
        """
        Initialise the TargetingPresetService.

        Parameters
        ----------
        app_name : str, optional
            The name of the application. Defaults to ``APP_NAME``.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        gam_version : str, optional
            The version of the API to use. Defaults to ``GAM_VERSION``.
        """
        ...

    def create(self, targeting: List[TargetingPreset]) -> None:
        """
        Create a list of targeting presets.

        Parameters
        ----------
        targeting : list[TargetingPreset]
            The list of targeting presets to create.
        """
        ...

    def update(self, targeting: List[TargetingPreset]) -> None:
        """
        Update a list of targeting presets.

        Parameters
        ----------
        targeting : list[TargetingPreset]
            The list of targeting presets to update.
        """
        ...

    def list_by_prefix(
        self, targeting_preset_prefix: str
    ) -> Dict[str, TargetingPreset]:
        """
        List targeting presets that match a given prefix.

        Parameters
        ----------
        targeting_preset_prefix : str
            The prefix to match against targeting preset names.

        Returns
        -------
        dict[str, TargetingPreset]
            A dictionary of targeting presets, keyed by name.
        """
        ...

class ReportService:
    """
    A wrapper for the Report service of the Ad Manager API.

    Methods
    -------
    gen_report_statement(ad_units=None, targeting_value_ids=None, order_id=None)
        Generate a statement for a report query.
    gen_report_query(report_statement, report_end=datetime.date.today(), report_days=1, dimensions=DIMENSIONS, metrics=METRICS, ad_unit_view=AdUnitView.TOP_LEVEL)
        Generate a report query job.
    normalise_report(data_frame)
        Normalise the column names of a report DataFrame.
    get_report_dataframe(ad_units=None, targeting_value_ids=None, report_date=datetime.date.today(), days=1, dimensions=DIMENSIONS, metrics=METRICS, ad_unit_view=AD_UNIT_VIEW)
        Get a report as a DataFrame.
    get_report_dataframe_by_statement(statement, report_date=datetime.date.today(), days=1, dimensions=DIMENSIONS, metrics=METRICS, ad_unit_view=AD_UNIT_VIEW)
        Get a report as a DataFrame, using a statement.
    """

    data_downloader: ad_manager.DataDownloader
    def __init__(
        self, app_name: str = ..., network_code: str = ..., gam_version: str = ...
    ) -> None:
        """
        Initialise the ReportService.

        Parameters
        ----------
        app_name : str, optional
            The name of the application. Defaults to ``APP_NAME``.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        gam_version : str, optional
            The version of the API to use. Defaults to ``GAM_VERSION``.
        """
        ...

    @staticmethod
    def gen_report_statement(
        ad_units: Optional[Union[int, List[int]]] = ...,
        targeting_value_ids: Optional[List[int]] = ...,
        order_id: Optional[Union[int, List[int]]] = ...,
    ) -> ad_manager.StatementBuilder:
        """
        Generate a statement for a report query.

        Parameters
        ----------
        ad_units : int or list[int], optional
            The ad unit IDs to filter by.
        targeting_value_ids : list[int], optional
            The custom targeting value IDs to filter by.
        order_id : int or list[int], optional
            The order IDs to filter by.

        Returns
        -------
        googleads.ad_manager.StatementBuilder
            The generated statement builder.
        """
        ...

    @staticmethod
    def gen_report_query(
        report_statement: ad_manager.StatementBuilder,
        report_end: datetime.date = ...,
        report_days: int = ...,
        dimensions: List[str] = ...,
        metrics: List[str] = ...,
        ad_unit_view: AdUnitView = ...,
    ) -> Dict[str, Any]:
        """
        Generate a report query job.

        Parameters
        ----------
        report_statement : googleads.ad_manager.StatementBuilder
            The statement for the report query.
        report_end : datetime.date, optional
            The end date for the report. Defaults to today.
        report_days : int, optional
            The number of days to include in the report. Defaults to 1.
        dimensions : list[str], optional
            The dimensions to include in the report. Defaults to ``DIMENSIONS``.
        metrics : list[str], optional
            The metrics to include in the report. Defaults to ``METRICS``.
        ad_unit_view : AdUnitView, optional
            The ad unit view for the report. Defaults to ``AdUnitView.TOP_LEVEL``.

        Returns
        -------
        dict[str, Any]
            The report query job.
        """
        ...

    @staticmethod
    def normalise_report(data_frame: pd.DataFrame) -> pd.DataFrame:
        """
        Normalise the column names of a report DataFrame.

        This method cleans up column names by stripping whitespace, converting
        to lowercase, replacing spaces and hyphens with underscores, and
        removing "column." and "dimension." prefixes. It also handles type
        conversion for numeric and date columns.

        Parameters
        ----------
        data_frame : pandas.DataFrame
            The report DataFrame to normalise.

        Returns
        -------
        pandas.DataFrame
            The normalised DataFrame.
        """
        ...

    def get_report_dataframe(
        self,
        ad_units: Optional[Union[int, List[int]]] = ...,
        targeting_value_ids: Optional[List[int]] = ...,
        report_date: datetime.date = ...,
        days: int = ...,
        dimensions: List[str] = ...,
        metrics: List[str] = ...,
        ad_unit_view: str = ...,
    ) -> pd.DataFrame:
        """
        Get a report as a DataFrame.

        Parameters
        ----------
        ad_units : int or list[int], optional
            The ad unit IDs to filter by.
        targeting_value_ids : list[int], optional
            The custom targeting value IDs to filter by.
        report_date : datetime.date, optional
            The end date for the report. Defaults to today.
        days : int, optional
            The number of days to include in the report. Defaults to 1.
        dimensions : list[str], optional
            The dimensions to include in the report. Defaults to ``DIMENSIONS``.
        metrics : list[str], optional
            The metrics to include in the report. Defaults to ``METRICS``.
        ad_unit_view : str, optional
            The ad unit view for the report. Defaults to ``AD_UNIT_VIEW``.

        Returns
        -------
        pandas.DataFrame
            The report data.
        """
        ...

    def get_report_dataframe_by_statement(
        self,
        statement: ad_manager.StatementBuilder,
        report_date: datetime.date = ...,
        days: int = ...,
        dimensions: List[str] = ...,
        metrics: List[str] = ...,
        ad_unit_view: str = ...,
    ) -> pd.DataFrame:
        """
        Get a report as a DataFrame, using a statement.

        Parameters
        ----------
        statement : googleads.ad_manager.StatementBuilder
            The statement for the report query.
        report_date : datetime.date, optional
            The end date for the report. Defaults to today.
        days : int, optional
            The number of days to include in the report. Defaults to 1.
        dimensions : list[str], optional
            The dimensions to include in the report. Defaults to ``DIMENSIONS``.
        metrics : list[str], optional
            The metrics to include in the report. Defaults to ``METRICS``.
        ad_unit_view : str, optional
            The ad unit view for the report. Defaults to ``AD_UNIT_VIEW``.

        Returns
        -------
        pandas.DataFrame
            The report data.
        """
        ...

class ForecastService:
    """
    A wrapper for the Forecast service of the Ad Manager API.

    Methods
    -------
    get_forecast(targetedAdUnits, creativePlaceholders, targets_list, report_date=datetime.datetime.now(tz=pytz.timezone(PYTZ_TIMEZONE)), days=30)
        Get a forecast for a given set of targeting criteria.
    get_forecast_by_targeting_preset(targetedAdUnits, creativePlaceholders, targeting_presets, report_date=datetime.datetime.now(tz=pytz.timezone(PYTZ_TIMEZONE)), days=30)
        Get a forecast by targeting presets.
    """

    _service_name = ...
    _gam_service: Any
    def __init__(
        self, app_name: str = ..., network_code: str = ..., gam_version: str = ...
    ) -> None:
        """
        Initialise the ForecastService.

        Parameters
        ----------
        app_name : str, optional
            The name of the application. Defaults to ``APP_NAME``.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        gam_version : str, optional
            The version of the API to use. Defaults to ``GAM_VERSION``.
        """
        ...

    def get_forecast(
        self,
        targetedAdUnits: List[Dict[str, Any]],
        creativePlaceholders: List[CreativePlaceholder],
        targets_list: List[Dict[str, Any]],
        report_date: datetime.datetime = ...,
        days: int = ...,
    ) -> List[ForecastItem]:
        """
        Get a forecast for a given set of targeting criteria.

        Parameters
        ----------
        targetedAdUnits : list[dict[str, Any]]
            The ad units to target.
        creativePlaceholders : list[CreativePlaceholder]
            The creative placeholders for the line item.
        targets_list : list[dict[str, Any]]
            The list of targeting criteria.
        report_date : datetime.datetime, optional
            The start date for the forecast. Defaults to now.
        days : int, optional
            The number of days to forecast. Defaults to 30.

        Returns
        -------
        list[ForecastItem]
            A list of forecast items.
        """
        ...

    def get_forecast_by_targeting_preset(
        self,
        targetedAdUnits: List[Dict[str, Any]],
        creativePlaceholders: List[CreativePlaceholder],
        targeting_presets: List[TargetingPreset],
        report_date: datetime.datetime = ...,
        days: int = ...,
    ) -> List[ForecastItem]:
        """
        Get a forecast by targeting presets.

        Parameters
        ----------
        targetedAdUnits : list[dict[str, Any]]
            The ad units to target.
        creativePlaceholders : list[CreativePlaceholder]
            The creative placeholders for the line item.
        targeting_presets : list[TargetingPreset]
            The targeting presets to use.
        report_date : datetime.datetime, optional
            The start date for the forecast. Defaults to now.
        days : int, optional
            The number of days to forecast. Defaults to 30.

        Returns
        -------
        list[ForecastItem]
            A list of forecast items.
        """
        ...

class TrafficService:
    """
    A wrapper for the Traffic service of the Ad Manager API.

    Methods
    -------
    get_traffic(inventory_targeting=None, custom_targeting=None, report_date=datetime.datetime.now(tz=pytz.timezone(PYTZ_TIMEZONE)), days=30)
        Get traffic data for a given set of targeting criteria.
    get_traffic_by_targeting_preset(inventory_targeting, targeting_preset, report_date=datetime.datetime.now(tz=pytz.timezone(PYTZ_TIMEZONE)), days=1)
        Get traffic data by targeting preset.
    """

    _service_name = ...
    _gam_service: Any
    def __init__(
        self, app_name: str = ..., network_code: str = ..., gam_version: str = ...
    ) -> None:
        """
        Initialise the TrafficService.

        Parameters
        ----------
        app_name : str, optional
            The name of the application. Defaults to ``APP_NAME``.
        network_code : str, optional
            The Ad Manager network code. Defaults to ``NETWORK_CODE``.
        gam_version : str, optional
            The version of the API to use. Defaults to ``GAM_VERSION``.
        """
        ...

    def get_traffic(
        self,
        inventory_targeting: Optional[Dict[str, Any]] = ...,
        custom_targeting: Optional[CustomCriteriaSet] = ...,
        report_date: datetime.datetime = ...,
        days: int = ...,
    ) -> List[trafficItem]:
        """
        Get traffic data for a given set of targeting criteria.

        Parameters
        ----------
        inventory_targeting : dict[str, Any], optional
            The inventory targeting. Defaults to the root ad unit.
        custom_targeting : CustomCriteriaSet, optional
            The custom targeting. Defaults to ``None``.
        report_date : datetime.datetime, optional
            The start date for the traffic data. Defaults to now.
        days : int, optional
            The number of days of traffic data to get. Defaults to 30.

        Returns
        -------
        list[trafficItem]
            A list of traffic items.
        """
        ...

    def get_traffic_by_targeting_preset(
        self,
        inventory_targeting: Dict[str, Any],
        targeting_preset: TargetingPreset,
        report_date: datetime.datetime = ...,
        days: int = ...,
    ) -> List[trafficItem]:
        """
        Get traffic data by targeting preset.

        Parameters
        ----------
        inventory_targeting : dict[str, Any]
            The inventory targeting.
        targeting_preset : TargetingPreset
            The targeting preset to use.
        report_date : datetime.datetime, optional
            The start date for the traffic data. Defaults to now.
        days : int, optional
            The number of days of traffic data to get. Defaults to 1.

        Returns
        -------
        list[trafficItem]
            A list of traffic items.
        """
        ...
