"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Any, Dict, List, Optional
from .Oauth import ServiceAccount

"""Wrapper for Google Analytics Reporting API."""

class Analytics:
    """
    High level helper for the Google Analytics Reporting API.

    Attributes
    ----------
    SCOPES : list[str]
        The scopes required for the Analytics API.

    Methods
    -------
    list_views()
        Return all accessible Analytics views.
    get_report(view_id, dimensions=["ga:source", "ga:medium"], metrics=["ga:sessions"], start_date="30daysAgo", end_date="yesterday")
        Return a report for a specific view as a DataFrame.
    get_all_reports(dimensions=["ga:source", "ga:medium"], metrics=["ga:sessions"], start_date="30daysAgo", end_date="yesterday")
        Fetch reports for all available views and combine them.
    report_to_df(analytics_report)
        Convert an Analytics API response to a DataFrame.
    """

    SCOPES = ...
    ServiceAccount = ServiceAccount
    _reporting: Any
    _management: Any
    def __init__(self, credentials: Optional[str] = ...) -> None:
        """
        Initialise Analytics API clients.

        Parameters
        ----------
        credentials : str, optional
            Path to a service account JSON file. If ``None``, the value from
            ``GOOGLE_APPLICATION_CREDENTIALS`` is used.
        """
        ...

    def list_views(self) -> List[Dict[str, Any]]:
        """
        Return all accessible Analytics views.

        Returns
        -------
        list[dict[str, Any]]
            A list of view objects.
        """
        ...

    def get_report(
        self,
        view_id: int,
        dimensions: List[str] = ...,
        metrics: List[str] = ...,
        start_date: str = ...,
        end_date: str = ...,
    ) -> pd.DataFrame:
        """
        Return a report for a specific view as a DataFrame.

        Parameters
        ----------
        view_id : int
            The ID of the view to query.
        dimensions : list[str], optional
            The dimensions to include in the report. Defaults to
            ``["ga:source", "ga:medium"]``.
        metrics : list[str], optional
            The metrics to include in the report. Defaults to ``["ga:sessions"]``.
        start_date : str, optional
            The start date of the report. Defaults to ``"30daysAgo"``.
        end_date : str, optional
            The end date of the report. Defaults to ``"yesterday"``.

        Returns
        -------
        pandas.DataFrame
            A DataFrame containing the report data.
        """
        ...

    def get_all_reports(
        self,
        dimensions: List[str] = ...,
        metrics: List[str] = ...,
        start_date: str = ...,
        end_date: str = ...,
    ) -> pd.DataFrame:
        """
        Fetch reports for all available views and combine them.

        Parameters
        ----------
        dimensions : list[str], optional
            The dimensions to include in the reports. Defaults to
            ``["ga:source", "ga:medium"]``.
        metrics : list[str], optional
            The metrics to include in the reports. Defaults to
            ``["ga:sessions"]``.
        start_date : str, optional
            The start date of the reports. Defaults to ``"30daysAgo"``.
        end_date : str, optional
            The end date of the reports. Defaults to ``"yesterday"``.

        Returns
        -------
        pandas.DataFrame
            A DataFrame containing the combined report data from all views.
        """
        ...

    @staticmethod
    def report_to_df(analytics_report: Dict[str, Any]) -> pd.DataFrame:
        """
        Convert an Analytics API response to a DataFrame.

        Parameters
        ----------
        analytics_report : dict[str, Any]
            The raw response from the Analytics API's ``batchGet`` method.

        Returns
        -------
        pandas.DataFrame
            A DataFrame containing the report data.
        """
        ...
