"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Union
from google.cloud import storage

"""Helpers for interacting with Google Cloud Storage."""

class CloudStorage:
    """
    Simple wrapper around the ``google.cloud.storage`` client.

    Attributes
    ----------
    __client : google.cloud.storage.Client
        The Cloud Storage client.

    Methods
    -------
    list_files(bucket_name, prefix)
        List blob names under ``prefix`` in ``bucket_name``.
    download_as_string(bucket_name, source_blob_name, destination_file_name)
        Download a JSON blob and save it locally.
    upload(bucket_name, destination_blob_name, data, override=True)
        Upload data to Cloud Storage.
    upload_from_string(bucket_name, destination_blob_name, data, override=False)
        Upload a string to Cloud Storage.
    upload_file_from_filename(local_file_path, destination_file_path, bucket_name, override=False)
        Upload a local file to Cloud Storage from a filename.
    upload_file(local_file_path, destination_file_path, override=False)
        Upload a file to a ``bucket_name/blob_path`` destination.
    upload_folder(local_folder, remote_folder, bucket_name, file_mask="*.gz", override=False)
        Upload all files in a local folder to Cloud Storage.
    file_exists(filepath, bucket_name)
        Return ``True`` if ``filepath`` exists in ``bucket_name``.
    delete_file(filename, bucket_name)
        Delete a single blob from Cloud Storage.
    delete_files(bucket_name, prefix)
        Delete all blobs with a given prefix.
    copy_file(bucket_name, file_name, destination_bucket_name, override=False)
        Copy a file between buckets.
    copy_files(bucket_name, prefix, destination_bucket_name, override=False)
        Copy all files with ``prefix`` to another bucket.
    """

    _client: storage.Client
    def __init__(
        self, credentials: Optional[str] = ..., project_id: Optional[str] = ...
    ) -> None:
        """
        Initialise the Cloud Storage client.

        Parameters
        ----------
        credentials : str, optional
            Path to a service account JSON file. Defaults to ``None`` which
            relies on environment configuration.
        project_id : str, optional
            Google Cloud project identifier. Defaults to ``None``.
        """
        ...

    def __enter__(self) -> CloudStorage:
        """
        Return the context manager instance.

        Returns
        -------
        CloudStorage
            The Cloud Storage client instance.
        """
        ...

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """
        Close the underlying client on context exit.

        Parameters
        ----------
        exc_type : Any
            The exception type.
        exc_val : Any
            The exception value.
        exc_tb : Any
            The traceback.
        """
        ...

    def list_files(self, bucket_name: str, prefix: str) -> List[str]:
        """
        List blob names under ``prefix`` in ``bucket_name``.

        Parameters
        ----------
        bucket_name : str
            The name of the bucket.
        prefix : str
            The prefix to filter by.

        Returns
        -------
        list[str]
            A list of blob names.
        """
        ...

    def download_as_string(
        self, bucket_name: str, source_blob_name: str, destination_file_name: str
    ) -> None:
        """
        Download a JSON blob and save it locally.

        Parameters
        ----------
        bucket_name : str
            The name of the bucket.
        source_blob_name : str
            The name of the blob to download.
        destination_file_name : str
            The local path to save the file to.
        """
        ...

    def upload(
        self,
        bucket_name: str,
        destination_blob_name: str,
        data: Union[str, object],
        override: bool = ...,
    ) -> None:
        """
        Upload data to Cloud Storage.

        Parameters
        ----------
        bucket_name : str
            The name of the bucket.
        destination_blob_name : str
            The name of the destination blob.
        data : str or object
            The data to upload.
        override : bool, optional
            Whether to override the blob if it already exists. Defaults to ``True``.
        """
        ...

    def upload_from_string(
        self,
        bucket_name: str,
        destination_blob_name: str,
        data: str,
        override: bool = ...,
    ) -> None:
        """
        Upload a string to Cloud Storage.

        Parameters
        ----------
        bucket_name : str
            The name of the bucket.
        destination_blob_name : str
            The name of the destination blob.
        data : str
            The string data to upload.
        override : bool, optional
            Whether to override the blob if it already exists. Defaults to ``False``.
        """
        ...

    def upload_file_from_filename(
        self,
        local_file_path: str,
        destination_file_path: str,
        bucket_name: str,
        override: bool = ...,
    ) -> None:
        """
        Upload a local file to Cloud Storage from a filename.

        Parameters
        ----------
        local_file_path : str
            The path to the local file.
        destination_file_path : str
            The destination path in the bucket.
        bucket_name : str
            The name of the bucket.
        override : bool, optional
            Whether to override the blob if it already exists. Defaults to ``False``.
        """
        ...

    def upload_file(
        self, local_file_path: str, destination_file_path: str, override: bool = ...
    ) -> None:
        """
        Upload a file to a ``bucket_name/blob_path`` destination.

        Parameters
        ----------
        local_file_path : str
            The path to the local file.
        destination_file_path : str
            The destination path in the format ``bucket_name/blob_path``.
        override : bool, optional
            Whether to override the blob if it already exists. Defaults to ``False``.
        """
        ...

    def upload_folder(
        self,
        local_folder: str,
        remote_folder: str,
        bucket_name: str,
        file_mask: str = ...,
        override: bool = ...,
    ) -> None:
        """
        Upload all files in a local folder to Cloud Storage.

        Parameters
        ----------
        local_folder : str
            The path to the local folder.
        remote_folder : str
            The destination path in the bucket.
        bucket_name : str
            The name of the bucket.
        file_mask : str, optional
            The file mask to match files in the local folder. Defaults to ``"*.gz"``.
        override : bool, optional
            Whether to override the blobs if they already exist. Defaults to ``False``.
        """
        ...

    def file_exists(self, filepath: str, bucket_name: str) -> bool:
        """
        Return ``True`` if ``filepath`` exists in ``bucket_name``.

        Parameters
        ----------
        filepath : str
            The path to the file in the bucket.
        bucket_name : str
            The name of the bucket.

        Returns
        -------
        bool
            ``True`` if the file exists, ``False`` otherwise.
        """
        ...

    def delete_file(self, filename: str, bucket_name: str) -> None:
        """
        Delete a single blob from Cloud Storage.

        Parameters
        ----------
        filename : str
            The name of the blob to delete.
        bucket_name : str
            The name of the bucket.
        """
        ...

    def delete_files(self, bucket_name: str, prefix: str) -> None:
        """
        Delete all blobs with a given prefix.

        Parameters
        ----------
        bucket_name : str
            The name of the bucket.
        prefix : str
            The prefix of the blobs to delete.
        """
        ...

    def copy_file(
        self,
        bucket_name: str,
        file_name: str,
        destination_bucket_name: str,
        override: bool = ...,
    ) -> bool:
        """
        Copy a file between buckets.

        Parameters
        ----------
        bucket_name : str
            The name of the source bucket.
        file_name : str
            The name of the file to copy.
        destination_bucket_name : str
            The name of the destination bucket.
        override : bool, optional
            Whether to override the file if it already exists. Defaults to ``False``.

        Returns
        -------
        bool
            ``True`` if the file was copied, ``False`` otherwise.
        """
        ...

    def copy_files(
        self,
        bucket_name: str,
        prefix: str,
        destination_bucket_name: str,
        override: bool = ...,
    ) -> None:
        """
        Copy all files with ``prefix`` to another bucket.

        Parameters
        ----------
        bucket_name : str
            The name of the source bucket.
        prefix : str
            The prefix of the files to copy.
        destination_bucket_name : str
            The name of the destination bucket.
        override : bool, optional
            Whether to override the files if they already exist. Defaults to ``False``.
        """
        ...
