"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from google.oauth2 import credentials, service_account
from googleads import oauth2
from googleads.oauth2 import GoogleOAuth2Client

"""OAuth helpers for Google APIs."""

class ClientCredentials:
    """
    Handle user or service account credentials.

    Attributes
    ----------
    credentials_path : str or None
        The path to the Google application credentials file.

    Methods
    -------
    gcp_credentials()
        Return Google Cloud credentials.
    get_service_account_client()
        Return a Google Ads service account client.
    get_cloudplatform(credentials_path=None, scopes=["https://www.googleapis.com/auth/cloud-platform"])
        Return Google Cloud credentials for the given scopes.
    """

    def __init__(self) -> None:
        """Initialise with credentials from ``GOOGLE_APPLICATION_CREDENTIALS``."""
        ...

    @property
    def gcp_credentials(
        self,
    ) -> Union[credentials.Credentials, service_account.Credentials]:
        """
        Return Google Cloud credentials.

        Returns
        -------
        google.oauth2.credentials.Credentials or google.oauth2.service_account.Credentials
            The generated credentials object.
        """
        ...

    @property
    def get_service_account_client(
        self,
    ) -> Union[oauth2.GoogleServiceAccountClient, GoogleOAuth2Client]:
        """
        Return a Google Ads service account client.

        Returns
        -------
        googleads.oauth2.GoogleServiceAccountClient or googleads.oauth2.GoogleOAuth2Client
            The Google Ads client.
        """
        ...

    def get_cloudplatform(
        self, credentials_path: Optional[str] = ..., scopes: Optional[List[str]] = ...
    ) -> Union[credentials.Credentials, service_account.Credentials]:
        """
        Return Google Cloud credentials for the given scopes.

        Parameters
        ----------
        credentials_path : str, optional
            Path to a service account JSON file. If ``None``, user credentials
            are used. Defaults to ``None``.
        scopes : list[str], optional
            The scopes to request. Defaults to ``["https://www.googleapis.com/auth/cloud-platform"]``.

        Returns
        -------
        google.oauth2.credentials.Credentials or google.oauth2.service_account.Credentials
            The generated credentials object.
        """
        ...

class ServiceAccount:
    """
    Helpers for service account authentication.

    Methods
    -------
    from_service_account_file(credentials=None, scopes=["https://www.googleapis.com/auth/cloud-platform"])
        Create credentials from a service account file.
    get_service_account_client(credentials=None, scope="ad_manager")
        Return a Google Ads service account client.
    """

    @staticmethod
    def from_service_account_file(
        credentials: Optional[str] = ..., scopes: Optional[List[str]] = ...
    ) -> service_account.Credentials:
        """
        Create credentials from a service account file.

        Parameters
        ----------
        credentials : str, optional
            Path to a service account JSON file. If ``None``, the value from
            ``GOOGLE_APPLICATION_CREDENTIALS`` is used.
        scopes : list[str], optional
            The scopes to request. Defaults to ``["https://www.googleapis.com/auth/cloud-platform"]``.

        Returns
        -------
        google.oauth2.service_account.Credentials
            The generated credentials object.
        """
        ...

    @staticmethod
    def get_service_account_client(
        credentials: Optional[str] = ..., scope: Optional[str] = ...
    ) -> oauth2.GoogleServiceAccountClient:
        """
        Return a Google Ads service account client.

        Parameters
        ----------
        credentials : str, optional
            Path to a service account JSON file. If ``None``, the value from
            ``GOOGLE_APPLICATION_CREDENTIALS`` is used.
        scope : str, optional
            The API scope to request. Defaults to ``"ad_manager"``.

        Returns
        -------
        googleads.oauth2.GoogleServiceAccountClient
            The Google Ads service account client.
        """
        ...
